=== marianapereira6/PRI2020/TP2/pr.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT project (dados,workteam,resumo,deliverables) >

<!ELEMENT dados (key_nome,titulo,subtitulo*,begin_date,end_date, supervisor) >
<!ELEMENT key_nome (#PCDATA) >
<!ELEMENT titulo (#PCDATA) >
<!ELEMENT subtitulo (#PCDATA) >
<!ELEMENT begin_date (#PCDATA) >
<!ELEMENT end_date (#PCDATA) >
<!ELEMENT supervisor (#PCDATA) >
<!ATTLIST supervisor 
            href CDATA #REQUIRED>

<!ELEMENT workteam (pessoas+) >
<!ELEMENT pessoas (nome,numero,email) >
<!ELEMENT nome (#PCDATA) >
<!ELEMENT numero (#PCDATA) >
<!ELEMENT email (#PCDATA) >


<!ELEMENT resumo (paragrafos+) >
<!ELEMENT paragrafos (#PCDATA|italico|bold|sublinhado|link)* >
<!ELEMENT italico (#PCDATA|bold|sublinhado|link)*>
<!ELEMENT bold (#PCDATA|italico|sublinhado|link)*>
<!ELEMENT sublinhado (#PCDATA|italico|bold|link)*>


<!ELEMENT deliverables (link+)  >
<!ELEMENT link (#PCDATA) >
<!ATTLIST link 
            href CDATA #REQUIRED>

=== marianapereira6/PRI2020/TP2/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project SYSTEM "file:/home/maraiana/Desktop/universidade/4%C2%BA%20ano/PLC/1%C2%BA%20semestre/2%20aula/pr.dtd">
<project>
    <dados>
        <key_nome>TP2</key_nome>
        <titulo>Trabalho de dtd e Xpath</titulo>
        <begin_date>19/10/2020</begin_date>
        <end_date>26/10/2020</end_date>
        <supervisor href="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho></supervisor>
    </dados>
    <workteam>
        <pessoas>
            <nome>Mariana de Oliveira Pereira</nome>
            <numero>A81146</numero>
            <email>a81146@alunos.uminho.pt</email>
        </pessoas>
    </workteam>
    <resumo>
        <paragrafos>Na primeira parte do TP2 consistia na realização do um dtd para um <bold>Project Record.</bold></paragrafos>
        <paragrafos>E na segunda parte realização de 3 perguntas em Xpath sobre os dados do <link href="http://www4.di.uminho.pt/~jcr/XML/didac/xmldocs/arq.xml"></link></paragrafos>
    </resumo>
    <deliverables>
        <link href="https://github.com/marianapereira6/PRI2020/blob/main/TP2/pr.dtd">DTD - Project Record</link>
        <link href="https://github.com/marianapereira6/PRI2020/edit/main/TP2/pr.xml">XML - Project Record</link>
        <link href="https://github.com/marianapereira6/PRI2020/blob/main/TP2/arq.xml">XML - arq</link>
        <link href=" https://github.com/marianapereira6/PRI2020/blob/main/TP2/arq.txt">Xpath - arq</link>
       
    </deliverables>
</project>

=== marianapereira6/PRI2020/TP3/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project SYSTEM "../2%20aula/pr.dtd">
<project>
    <dados>
        <key_nome>TP3</key_nome>
        <titulo>Stylesheet do arq.xml</titulo>
        <begin_date>26/10/20</begin_date>
        <end_date>02/11/20</end_date>
        <supervisor href="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho></supervisor>
    </dados>
    <workteam>
        <pessoas>
            <nome>Mariana de Oliveira Pereira</nome>
            <numero>A81146</numero>
            <email>a81146@alunos.uminho.pt</email>
        </pessoas>
    </workteam>
    <resumo>
        <paragrafos>Primeira do TP3 consistia na realização de um dtd para o arq.xml.</paragrafos>
        <paragrafos>Em segida a realização de uma xsl para o mesmo ficheiro, criando um indice de navegação. Neste indice usei a identi para odenação alfabética.</paragrafos>
    </resumo>
    <deliverables>
        <link href=""></link>
    </deliverables>
</project>
